# Generated by Django 4.0.5 on 2022-06-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text="enter the author's name", max_length=200, verbose_name='Author')),
                ('title', models.CharField(help_text='enter the title of the report', max_length=200, verbose_name='Title')),
                ('research_year', models.CharField(help_text='enter the year of archaeological research', max_length=20, verbose_name='Research Year')),
                ('report_year', models.CharField(help_text='enter the year of the research report', max_length=20, verbose_name='Report Year')),
                ('research_object_nr', models.IntegerField(help_text='enter the research object number', verbose_name='Research Object Number')),
            ],
        ),
    ]
