# Generated by Django 4.0.5 on 2022-06-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliography',
            name='record_nr',
            field=models.IntegerField(help_text='temporary field, ID from old database', null=True, verbose_name='Record Number'),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='research_object_nr',
            field=models.IntegerField(help_text='enter the research object number', null=True, verbose_name='Research Object Number'),
        ),
    ]
