# Generated by Django 4.0.5 on 2022-06-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0002_bibliography_record_nr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliography',
            name='report_year',
            field=models.CharField(help_text='enter the year of the research report', max_length=100, verbose_name='Report Year'),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='research_year',
            field=models.CharField(help_text='enter the year of archaeological research', max_length=100, verbose_name='Research Year'),
        ),
    ]
