# Generated by Django 4.0.5 on 2022-06-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0004_alter_bibliography_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliography',
            name='author',
            field=models.CharField(help_text="enter the author's name", max_length=250, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='title',
            field=models.CharField(help_text='enter the title of the report', max_length=700, verbose_name='Title'),
        ),
    ]
