# Generated by Django 4.0.5 on 2022-06-30 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0005_alter_bibliography_author_alter_bibliography_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliographicReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='enter a bibliographic reference (archive, document number, etc.)', max_length=200, verbose_name='Bibliographic Reference')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archeological_pottery_forms.bibliography')),
            ],
        ),
    ]
