# Generated by Django 4.0.5 on 2022-06-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0006_bibliographicreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibliography',
            name='record_nr',
        ),
    ]
