# Generated by Django 4.0.5 on 2022-06-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0007_remove_bibliography_record_nr'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotteryLipForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lip_form', models.ImageField(null=True, upload_to='images', verbose_name='Lip form')),
                ('lip_nr', models.IntegerField(help_text='temporary field, lip number from old database', null=True, verbose_name='old lip number')),
            ],
        ),
        migrations.CreateModel(
            name='PotteryOrnamentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ornament_form', models.ImageField(null=True, upload_to='images', verbose_name='Ornament form')),
                ('ornament_nr', models.IntegerField(help_text='temporary field, ornament number from old database', null=True, verbose_name='old lip number')),
            ],
        ),
    ]
