# Generated by Django 4.0.5 on 2022-06-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0008_potterylipform_potteryornamentform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potteryornamentform',
            name='ornament_nr',
            field=models.IntegerField(help_text='temporary field, ornament number from old database', null=True, verbose_name='old ornament number'),
        ),
    ]
