# Generated by Django 4.0.5 on 2022-06-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0009_alter_potteryornamentform_ornament_nr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PotteryLipForm',
            new_name='PotteryLipShape',
        ),
        migrations.RenameModel(
            old_name='PotteryOrnamentForm',
            new_name='PotteryOrnamentShape',
        ),
    ]
