# Generated by Django 4.0.5 on 2022-06-30 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0010_rename_potterylipform_potterylipshape_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliographicreference',
            name='reference',
            field=models.CharField(help_text='enter a bibliographic reference (archive, document number, etc.)', max_length=200, verbose_name='bibliographic reference'),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='author',
            field=models.CharField(help_text="enter the author's name", max_length=250, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='report_year',
            field=models.CharField(help_text='enter the year of the research report', max_length=100, verbose_name='report year'),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='research_object_nr',
            field=models.IntegerField(help_text='enter the research object number', null=True, verbose_name='research object number'),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='research_year',
            field=models.CharField(help_text='enter the year of archaeological research', max_length=100, verbose_name='research year'),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='title',
            field=models.CharField(help_text='enter the title of the report', max_length=700, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='potteryornamentshape',
            name='ornament_form',
            field=models.ImageField(null=True, upload_to='images', verbose_name='ornament form'),
        ),
        migrations.CreateModel(
            name='PotteryDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find_registration_nr', models.CharField(help_text='enter the registration number of the archaeological find', max_length=20, verbose_name='registration number')),
                ('arc_length', models.IntegerField(help_text='enter length of lip arc (milimeters)', null=True, verbose_name='arc length')),
                ('color', models.CharField(help_text='color of archaeological find', max_length=10, verbose_name='color')),
                ('note', models.CharField(help_text='enter some text you need', max_length=500, verbose_name='note')),
                ('research_object_nr', models.IntegerField(help_text='enter the research object number', null=True, verbose_name='research object number')),
                ('lip_nr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archeological_pottery_forms.potterylipshape')),
                ('ornament_nr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archeological_pottery_forms.potteryornamentshape')),
            ],
        ),
    ]
