# Generated by Django 4.0.5 on 2022-07-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0011_alter_bibliographicreference_reference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potterydescription',
            old_name='lip_nr',
            new_name='lip',
        ),
        migrations.RenameField(
            model_name='potterydescription',
            old_name='ornament_nr',
            new_name='ornament',
        ),
        migrations.AddField(
            model_name='potterydescription',
            name='neck_nr',
            field=models.IntegerField(help_text='temporary field, neck id from old database', null=True, verbose_name='neck number'),
        ),
    ]
