# Generated by Django 4.0.5 on 2022-07-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0012_rename_lip_nr_potterydescription_lip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potterydescription',
            name='color',
            field=models.CharField(help_text='color of archaeological find', max_length=10, null=True, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='potterydescription',
            name='note',
            field=models.CharField(help_text='enter some text you need', max_length=500, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='potterydescription',
            name='research_object_nr',
            field=models.IntegerField(help_text='enter research object number', null=True, verbose_name='research object number'),
        ),
    ]
