# Generated by Django 4.0.5 on 2022-07-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0014_alter_bibliography_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliography',
            options={'ordering': ['research_year'], 'verbose_name': 'report', 'verbose_name_plural': 'reports'},
        ),
        migrations.AlterField(
            model_name='bibliographicreference',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='archeological_pottery_forms.bibliography'),
        ),
        migrations.AlterField(
            model_name='potterydescription',
            name='lip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='archeological_pottery_forms.potterylipshape'),
        ),
        migrations.AlterField(
            model_name='potterydescription',
            name='ornament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='archeological_pottery_forms.potteryornamentshape'),
        ),
    ]
