# Generated by Django 4.0.5 on 2022-07-04 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0015_alter_bibliography_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliography',
            options={'ordering': ['report_year'], 'verbose_name': 'report', 'verbose_name_plural': 'reports'},
        ),
    ]
