# Generated by Django 4.0.5 on 2022-07-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0016_alter_bibliography_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliographicreference',
            options={'ordering': ['reference'], 'verbose_name': 'reference', 'verbose_name_plural': 'references'},
        ),
    ]
