# Generated by Django 4.0.5 on 2022-07-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0018_researchobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='potterydescription',
            options={'ordering': ['research_object_nr_old', 'find_registration_nr']},
        ),
        migrations.RenameField(
            model_name='bibliography',
            old_name='research_object_nr',
            new_name='research_object_nr_old',
        ),
        migrations.RenameField(
            model_name='potterydescription',
            old_name='research_object_nr',
            new_name='research_object_nr_old',
        ),
    ]
