# Generated by Django 4.0.5 on 2022-07-07 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0019_alter_potterydescription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliography',
            name='research_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='archeological_pottery_forms.researchobject'),
        ),
        migrations.AddField(
            model_name='potterydescription',
            name='research_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='archeological_pottery_forms.researchobject'),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='research_object_nr_old',
            field=models.IntegerField(help_text='enter the research object number', null=True, verbose_name='old research object number'),
        ),
        migrations.AlterField(
            model_name='potterydescription',
            name='research_object_nr_old',
            field=models.IntegerField(help_text='enter research object number', null=True, verbose_name='old research object number'),
        ),
    ]
