# Generated by Django 4.0.5 on 2022-07-07 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0020_bibliography_research_object_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='potterydescription',
            options={'ordering': ['research_object', 'find_registration_nr']},
        ),
        migrations.RemoveField(
            model_name='bibliography',
            name='research_object_nr_old',
        ),
        migrations.RemoveField(
            model_name='potterydescription',
            name='research_object_nr_old',
        ),
    ]
