# Generated by Django 4.0.5 on 2022-07-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0021_alter_potterydescription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotteryMakingActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='action')),
            ],
        ),
        migrations.AddField(
            model_name='potterylipshape',
            name='action',
            field=models.ManyToManyField(to='archeological_pottery_forms.potterymakingactions'),
        ),
        migrations.AddField(
            model_name='potteryornamentshape',
            name='action',
            field=models.ManyToManyField(to='archeological_pottery_forms.potterymakingactions'),
        ),
    ]
