# Generated by Django 4.0.5 on 2022-07-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0022_potterymakingactions_potterylipshape_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='potterymakingactions',
            name='sequence',
            field=models.IntegerField(null=True, verbose_name='sequence'),
        ),
    ]
