# Generated by Django 4.0.5 on 2022-07-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0023_potterymakingactions_sequence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PotteryMakingActions',
            new_name='PotteryMakingAction',
        ),
    ]
