# Generated by Django 4.0.5 on 2022-07-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0024_rename_potterymakingactions_potterymakingaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='potterymakingaction',
            options={'ordering': ['sequence', 'action']},
        ),
    ]
