# Generated by Django 4.0.5 on 2022-07-12 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archeological_pottery_forms', '0026_alter_researchobject_research_object_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='potterydescription',
            name='researcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
