# Generated by Django 4.0.5 on 2022-07-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0027_potterydescription_researcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potterydescription',
            name='arc_length',
            field=models.IntegerField(blank=True, help_text='enter length of lip arc (milimeters)', null=True, verbose_name='arc length'),
        ),
        migrations.AlterField(
            model_name='potterydescription',
            name='color',
            field=models.CharField(blank=True, help_text='color of archaeological find', max_length=10, null=True, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='potterydescription',
            name='lip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='archeological_pottery_forms.potterylipshape'),
        ),
        migrations.AlterField(
            model_name='potterydescription',
            name='neck_nr',
            field=models.IntegerField(blank=True, help_text='temporary field, neck id from old database', null=True, verbose_name='neck number'),
        ),
        migrations.AlterField(
            model_name='potterydescription',
            name='note',
            field=models.CharField(blank=True, help_text='enter some text you need', max_length=500, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='potterydescription',
            name='ornament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='archeological_pottery_forms.potteryornamentshape'),
        ),
    ]
