# Generated by Django 4.0.5 on 2022-07-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0031_remove_potterydescription_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='potterydescription',
            name='drawing',
            field=models.ImageField(null=True, upload_to='pottery_form_types', verbose_name='drawing'),
        ),
    ]
