# Generated by Django 4.0.5 on 2022-07-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0032_potterydescription_drawing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potterydescription',
            name='drawing',
        ),
    ]
