# Generated by Django 4.0.5 on 2022-07-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0034_potterydescription_drawing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeramicContour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(verbose_name='x')),
                ('y', models.IntegerField(verbose_name='y')),
                ('find', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archeological_pottery_forms.potterydescription')),
            ],
        ),
    ]
