# Generated by Django 4.0.5 on 2022-07-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0035_ceramiccontour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potterydescription',
            name='drawing',
        ),
        migrations.AlterField(
            model_name='ceramiccontour',
            name='find',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='archeological_pottery_forms.potterydescription'),
        ),
    ]
