# Generated by Django 4.0.5 on 2022-07-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0036_remove_potterydescription_drawing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='potterydescription',
            name='distance_to_center',
            field=models.IntegerField(blank=True, help_text='distance from  profile min x coordinate to the center of pot', null=True, verbose_name='distance to center'),
        ),
    ]
