# Generated by Django 4.0.5 on 2022-07-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0037_potterydescription_distance_to_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='potterydescription',
            name='profile_reviewed',
            field=models.BooleanField(default=False, verbose_name='profile reviewed'),
        ),
        migrations.AlterField(
            model_name='potterydescription',
            name='distance_to_center',
            field=models.IntegerField(blank=True, help_text='distance from  profile min x coordinate to the center of pot (mm*5)', null=True, verbose_name='distance to center'),
        ),
    ]
