# Generated by Django 4.0.5 on 2022-07-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0038_potterydescription_profile_reviewed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContourCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find_1', models.IntegerField(verbose_name='find_1')),
                ('find_2', models.IntegerField(verbose_name='find_2')),
                ('correlation', models.FloatField(verbose_name='correlation')),
            ],
        ),
    ]
