# Generated by Django 4.0.5 on 2022-07-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0039_contourcorrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contourcorrelation',
            name='length_compared',
            field=models.FloatField(blank=True, null=True, verbose_name='length_compared'),
        ),
    ]
