# Generated by Django 4.0.5 on 2022-07-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0040_contourcorrelation_length_compared'),
    ]

    operations = [
        migrations.AddField(
            model_name='potterydescription',
            name='correlation_calculated',
            field=models.BooleanField(default=False, verbose_name='correlation_calculated'),
        ),
    ]
