# Generated by Django 4.0.5 on 2022-07-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0041_potterydescription_correlation_calculated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contourcorrelation',
            name='correlation',
        ),
        migrations.AddField(
            model_name='contourcorrelation',
            name='correlation_width',
            field=models.FloatField(blank=True, null=True, verbose_name='correlation_width'),
        ),
        migrations.AddField(
            model_name='contourcorrelation',
            name='correlation_x',
            field=models.FloatField(blank=True, null=True, verbose_name='correlation_x'),
        ),
    ]
