# Generated by Django 4.0.5 on 2022-07-31 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0042_remove_contourcorrelation_correlation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContourGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='note')),
            ],
        ),
        migrations.AddField(
            model_name='potterydescription',
            name='contour_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='archeological_pottery_forms.contourgroup'),
        ),
    ]
