# Generated by Django 4.0.5 on 2022-07-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0043_contourgroup_potterydescription_contour_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='potterydescription',
            name='arc_angle',
            field=models.FloatField(blank=True, null=True, verbose_name='arc_angle'),
        ),
    ]
