# Generated by Django 4.0.5 on 2022-07-31 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0044_potterydescription_arc_angle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potterydescription',
            name='arc_angle',
        ),
    ]
