# Generated by Django 4.0.5 on 2022-08-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0045_remove_potterydescription_arc_angle'),
    ]

    operations = [
        migrations.AddField(
            model_name='potterydescription',
            name='arc_angle',
            field=models.FloatField(blank=True, null=True, verbose_name='arc angle'),
        ),
        migrations.AddField(
            model_name='potterydescription',
            name='find_length',
            field=models.FloatField(blank=True, null=True, verbose_name='find length'),
        ),
    ]
