# Generated by Django 4.0.5 on 2022-08-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0046_potterydescription_arc_angle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potterydescription',
            name='distance_to_center',
        ),
    ]
