# Generated by Django 4.0.5 on 2022-10-19 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0048_remove_potterydescription_contour_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='potterydescription',
            name='contour_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='archeological_pottery_forms.contourgroup'),
        ),
    ]
