# Generated by Django 4.0.5 on 2022-10-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0049_potterydescription_contour_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potterydescription',
            old_name='group',
            new_name='groups',
        ),
    ]
