# Generated by Django 4.0.5 on 2022-10-20 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0052_remove_contourcorrelation_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='contourcorrelation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correlations', to='archeological_pottery_forms.contourgroup'),
        ),
    ]
