# Generated by Django 4.0.5 on 2022-11-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0056_alter_potterydescription_bottom_base_y_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potterydescription',
            name='bottom_base_y',
        ),
        migrations.AddField(
            model_name='potterydescription',
            name='bottom_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='bottom_y'),
        ),
    ]
