# Generated by Django 4.0.5 on 2022-11-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0058_remove_potterydescription_contour_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potterydescription',
            name='neck_nr',
        ),
    ]
