# Generated by Django 4.0.5 on 2022-11-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0059_remove_potterydescription_neck_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='potterydescription',
            name='neck_shoulders_union',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='neck_shoulders_union'),
        ),
        migrations.AddField(
            model_name='potterydescription',
            name='neck_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='neck_type'),
        ),
        migrations.AddField(
            model_name='potterydescription',
            name='shoulders_body_union',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='shoulders_body_union'),
        ),
        migrations.AddField(
            model_name='potterydescription',
            name='shoulders_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='shoulders_type'),
        ),
    ]
