# Generated by Django 4.0.5 on 2022-11-17 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0061_remove_potterydescription_neck_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContourNodeDeviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviation', models.IntegerField(verbose_name='deviation')),
                ('node', models.CharField(max_length=100, verbose_name='node')),
                ('find', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviation', to='archeological_pottery_forms.potterydescription')),
            ],
        ),
    ]
