# Generated by Django 4.0.5 on 2022-11-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0062_contournodedeviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contournodedeviation',
            name='node',
            field=models.CharField(max_length=20, verbose_name='node'),
        ),
    ]
