# Generated by Django 4.0.5 on 2022-12-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0063_alter_contournodedeviation_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='potterydescription',
            name='bottom_exist',
            field=models.BooleanField(default=False, verbose_name='bottom_exist'),
        ),
        migrations.AddField(
            model_name='potterydescription',
            name='neck_max_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='neck_max_y'),
        ),
        migrations.AddField(
            model_name='potterydescription',
            name='neck_min_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='neck_min_y'),
        ),
        migrations.AddField(
            model_name='potterydescription',
            name='shoulders_max_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='shoulders_max_y'),
        ),
        migrations.AddField(
            model_name='potterydescription',
            name='shoulders_min_y',
            field=models.IntegerField(blank=True, null=True, verbose_name='shoulders_min_y'),
        ),
    ]
