# Generated by Django 4.0.5 on 2022-12-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0064_potterydescription_bottom_exist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potterydescription',
            name='bottom_y',
        ),
    ]
