# Generated by Django 4.0.5 on 2022-12-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0066_remove_potterydescription_neck_base_y_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContourNodeDeviation',
        ),
    ]
