# Generated by Django 4.0.5 on 2022-12-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0067_delete_contournodedeviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contourcorrelation',
            name='correlation_x_body',
            field=models.FloatField(blank=True, null=True, verbose_name='correlation_x_body'),
        ),
        migrations.AddField(
            model_name='contourcorrelation',
            name='correlation_x_neck',
            field=models.FloatField(blank=True, null=True, verbose_name='correlation_x_neck'),
        ),
        migrations.AddField(
            model_name='contourcorrelation',
            name='correlation_x_shoulders',
            field=models.FloatField(blank=True, null=True, verbose_name='correlation_x_shoulders'),
        ),
    ]
