# Generated by Django 4.0.5 on 2022-12-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0068_contourcorrelation_correlation_x_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contourgroup',
            name='length_group',
            field=models.IntegerField(null=True, verbose_name='length_group'),
        ),
    ]
