# Generated by Django 4.0.5 on 2022-12-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0071_contourgroup_correlation_avg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contourgroup',
            name='correlation_avg',
        ),
    ]
