# Generated by Django 4.0.5 on 2022-12-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0073_potterydescription_neck_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='potterydescription',
            name='neck_slope',
            field=models.FloatField(blank=True, null=True, verbose_name='neck_slope'),
        ),
        migrations.AddField(
            model_name='potterydescription',
            name='shoulders_slope',
            field=models.FloatField(blank=True, null=True, verbose_name='shoulders_slope'),
        ),
    ]
