# Generated by Django 4.0.5 on 2022-12-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0075_potterylipshape_relative_lip'),
    ]

    operations = [
        migrations.AddField(
            model_name='potterylipshape',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='note'),
        ),
    ]
