# Generated by Django 4.0.5 on 2023-02-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0078_potteryornamentshape_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceramiccontour',
            name='curvature',
            field=models.FloatField(blank=True, null=True, verbose_name='curvature'),
        ),
    ]
