# Generated by Django 4.0.5 on 2023-02-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0080_remove_contourcorrelation_correlation_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceramiccontour',
            name='profile_side',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='profile_side'),
        ),
    ]
