# Generated by Django 4.0.5 on 2023-02-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0081_ceramiccontour_profile_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='contourcorrelation',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='area'),
        ),
    ]
