# Generated by Django 4.0.5 on 2023-02-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0082_contourcorrelation_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contourgroup',
            name='length_group',
        ),
        migrations.AddField(
            model_name='contourgroup',
            name='precision',
            field=models.IntegerField(blank=True, null=True, verbose_name='precision'),
        ),
    ]
