# Generated by Django 4.0.5 on 2023-02-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archeological_pottery_forms', '0083_remove_contourgroup_length_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contourgroup',
            name='precision',
            field=models.FloatField(blank=True, null=True, verbose_name='precision'),
        ),
    ]
